using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Management;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using System.Web.Script.Serialization;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;

namespace Wintools {
    internal sealed class ServiceState {
        public string Name {get;set;}
        public string Label {get;set;}
        public string State {get;set;}
        public string Mode {get;set;}
        public string RunningLabel {get{return State=="Running"?"Работает":State=="Stopped"?"Остановлена":State=="Paused"?"Приостановлена":"Переход: "+State;}}
        public string StartLabel {get{return Mode=="Auto"?"Автоматический":Mode=="Manual"?"Вручную / по запросу":Mode=="Disabled"?"Отключён":Mode;}}
        public string Title { get { return Label+" ("+Name+")"; } }
        public string Detail { get { return "Сейчас: "+(State=="Running"?"работает":State=="Stopped"?"остановлена":State=="Paused"?"приостановлена":"переходное состояние: "+State)+" · Запуск: "+(Mode=="Auto"?"автоматический":Mode=="Manual"?"вручную / по запросу Windows":Mode=="Disabled"?"отключён":Mode); } }
        public override string ToString(){return Title+Environment.NewLine+Detail;}
    }
    internal sealed partial class MainWindow {
        private ServiceState[] services;
        private bool readingServices;
        private bool servicesPending;
        private int serviceEpoch;
        private TextBlock serviceStatus, healthStatus, healthResult, verificationStatus, verificationResult;
        private TextBox serviceSearch;
        private CheckBox runningOnly;
        private ListBox serviceList;
        private Button serviceRefresh, healthStart, verificationStart;
        private ProgressBar healthProgress;
        private string priorMemory;
        private static TextBlock Paragraph(string text){return new TextBlock{Text=text,TextWrapping=TextWrapping.Wrap,Margin=new Thickness(0,0,0,14)};}
        private Button ToolButton(StackPanel panel,string caption,Action action){var button=new Button{Content=caption,HorizontalAlignment=HorizontalAlignment.Left,Margin=new Thickness(0,0,0,14)};button.Click+=(s,e)=>action();panel.Children.Add(button);return button;}
        private StackPanel ToolPage(string name){var panel=new StackPanel{Margin=new Thickness(4)};var scroll=new ScrollViewer{Content=panel,VerticalScrollBarVisibility=ScrollBarVisibility.Auto,Visibility=Visibility.Collapsed};Window.RegisterName(name,scroll);((Grid)Get<FrameworkElement>("SettingsPage").Parent).Children.Add(scroll);return panel;}
        private void InitializeHealth(){
            InitializeServiceBrowser();
            var panel=ToolPage("HealthPage");InitializeMonitor(panel);panel.Children.Add(Paragraph("Проверка читает загрузку процессора, доступную оперативную память, свободное место на дисках, список автозагрузки и самые крупные процессы в памяти. Настройки не меняются, файлы не удаляются. Это снимок текущего состояния, а не тест скорости или оценка FPS."));
            healthStart=ToolButton(panel,"Проверить состояние ПК",async()=>await ReadHealth());healthProgress=new ProgressBar{Height=4,IsIndeterminate=true,Visibility=Visibility.Collapsed,Margin=new Thickness(0,0,0,14)};panel.Children.Add(healthProgress);healthStatus=Paragraph("Проверка ещё не выполнялась.");panel.Children.Add(healthStatus);healthResult=Paragraph("");panel.Children.Add(healthResult);ToolButton(panel,"Что можно улучшить →",()=>ShowPage(8));
            panel=ToolPage("VerificationPage");panel.Children.Add(Paragraph("Сверяем записи истории Wintools с текущими настройками Windows: реестром, типом запуска служб и другими поддерживаемыми параметрами. Так можно заметить, что обновление Windows или другая программа изменила настройку. Проверка ничего не исправляет и не оценивает скорость ПК. Повторные записи одного действия проверяются отдельно."));verificationStart=ToolButton(panel,"Сверить настройки с историей",async()=>await ReadVerification());verificationStatus=Paragraph("Совпадает — настройка соответствует каталогу. Изменилась — текущее значение отличается. Не проверено — для записи нет доступной проверки. Отменённые действия пропускаются.");panel.Children.Add(verificationStatus);verificationResult=Paragraph("");panel.Children.Add(verificationResult);ToolButton(panel,"Открыть историю и откат →",()=>ShowPage(1));
            panel=ToolPage("OptimizationPage");panel.Children.Add(Paragraph("Начните со снимка состояния ПК, изменяйте по одному пункту и повторяйте проверку при той же нагрузке. Эти инструменты открывают штатные настройки Windows; решение об изменении остаётся за вами."));ToolButton(panel,"Снять показатели ПК →",()=>ShowPage(6));
            AddAdvice(panel,"Ускорить вход в Windows","В автозагрузке отключите приложения, которые не нужны сразу после входа. Сохраните защиту, драйверы и нужную синхронизацию. В Диспетчере задач можно посмотреть влияние приложения на запуск.","ms-settings:startupapps");
            AddAdvice(panel,"Освободить место на диске","Просмотрите категории хранилища и настройте Контроль памяти. Перед очисткой проверьте корзину и загрузки: удаление файлов может быть необратимым.","ms-settings:storagesense");
            AddAdvice(panel,"Настроить визуальные эффекты","На слабом ПК отключение анимации может сделать интерфейс отзывчивее. В окне параметров быстродействия можно сохранить сглаживание экранных шрифтов.",Path.Combine(Environment.SystemDirectory,"SystemPropertiesPerformance.exe"));
            AddAdvice(panel,"Проверить питание","Повышенная производительность расходует больше энергии и усиливает нагрев. На ноутбуке сравнивайте результат при подключённом питании.","ms-settings:powersleep");
            AddAdvice(panel,"Проверить обслуживание SSD и HDD","Откройте «Оптимизация дисков» и проверьте расписание. Windows выбирает обслуживание по типу накопителя. Отключать эту службу ради ускорения не требуется.",Path.Combine(Environment.SystemDirectory,"dfrgui.exe"));
            AddAdvice(panel,"Найти программу, создающую нагрузку","Сортируйте процессы по ЦП, памяти или диску. Закрывайте только знакомые приложения с сохранёнными документами.",Path.Combine(Environment.SystemDirectory,"Taskmgr.exe"));
            ToolButton(panel,"Рекомендации Microsoft ↗",()=>OpenTool("https://support.microsoft.com/en-us/windows/experience/performance-optimization/tips-to-improve-pc-performance-in-windows"));
            ClickAsync("NavServices",async()=>{if(services==null)await RefreshServices();});
            ClickAsync("RefreshCatalogueServices",async()=>await RefreshServices());
        }
        private void AddAdvice(StackPanel panel,string title,string description,string target){var card=new Border{Padding=new Thickness(18),CornerRadius=new CornerRadius(12),Margin=new Thickness(0,0,0,14)};card.SetResourceReference(Border.BackgroundProperty,"Surface");var content=new StackPanel();card.Child=content;var heading=Paragraph(title);heading.FontSize=19;heading.FontWeight=FontWeights.SemiBold;content.Children.Add(heading);content.Children.Add(Paragraph(description));ToolButton(content,"Открыть настройки ↗",()=>OpenTool(target));panel.Children.Add(card);}
        private void OpenTool(string target){try{Process.Start(new ProcessStartInfo(target){UseShellExecute=true});}catch(Exception ex){Text("Status","Не удалось открыть инструмент Windows: "+ex.Message);}}
        private async Task RefreshServices(){if(busy)return;if(readingServices){servicesPending=true;return;}int epoch=serviceEpoch;readingServices=true;serviceRefresh.IsEnabled=false;Enabled("RefreshCatalogueServices",false);Filter();serviceStatus.Text="Читаем установленные службы и способы их запуска…";try{var snapshot=await Task.Run(()=>{var result=new List<ServiceState>();using(var searcher=new ManagementObjectSearcher("SELECT Name,DisplayName,State,StartMode FROM Win32_Service")){searcher.Options.Timeout=TimeSpan.FromSeconds(20);using(var rows=searcher.Get())foreach(ManagementObject row in rows){using(row)result.Add(new ServiceState{Name=Convert.ToString(row["Name"]),Label=Convert.ToString(row["DisplayName"]),State=Convert.ToString(row["State"]),Mode=Convert.ToString(row["StartMode"])});}}return result.OrderBy(r=>r.Label).ToArray();});if(closed||busy||epoch!=serviceEpoch)return;services=snapshot;FilterServices();serviceStatus.Text="Снимок на "+DateTime.Now.ToString("HH:mm:ss")+" · Всего: "+services.Length+" · Работают: "+services.Count(r=>r.State=="Running")+" · Автозапуск: "+services.Count(r=>r.Mode=="Auto")+". Состояние меняется со временем — обновляйте снимок.";Filter();}catch(Exception ex){if(!closed){services=null;FilterServices();serviceStatus.Text="Не удалось прочитать службы. Их состояние неизвестно. "+ex.Message;Filter();}}finally{readingServices=false;if(!closed){serviceRefresh.IsEnabled=!busy;Enabled("RefreshCatalogueServices",!busy);Filter();if(servicesPending&&!busy){servicesPending=false;var pendingRefresh=Window.Dispatcher.BeginInvoke(new Action(async()=>await RefreshServices()));}}}}
        private void FilterServices(){if(serviceList==null)return;var query=serviceSearch.Text.Trim();var selected=serviceList.SelectedItem as ServiceState;int mode=serviceMode==null?0:serviceMode.SelectedIndex;serviceList.ItemsSource=(services??new ServiceState[0]).Where(r=>(mode==0||(mode==1&&r.Mode=="Auto")||(mode==2&&r.Mode=="Manual")||(mode==3&&r.Mode=="Disabled")||(mode==4&&catalogue.Any(t=>t.Kind=="SVC"&&string.Equals(t.Target,r.Name,StringComparison.OrdinalIgnoreCase))))&&(runningOnly.IsChecked!=true||r.State=="Running")&&(query.Length==0||r.Title.IndexOf(query,StringComparison.CurrentCultureIgnoreCase)>=0)).ToArray();if(selected!=null)serviceList.SelectedItem=serviceList.Items.Cast<ServiceState>().FirstOrDefault(r=>r.Name==selected.Name);}
        private string InlineServiceStatus(Tweak item){if(item.Kind!="SVC")return "";if(services==null)return readingServices?"Читаем состояние службы…":"Состояние неизвестно · нажмите ↻";var state=services.FirstOrDefault(s=>string.Equals(s.Name,item.Target,StringComparison.OrdinalIgnoreCase));return state==null?"Не установлена на этом ПК":state.Detail;}
        private string ServiceDetail(Tweak item){if(item==null||item.Kind!="SVC")return "";var state=services==null?null:services.FirstOrDefault(s=>string.Equals(s.Name,item.Target,StringComparison.OrdinalIgnoreCase));return "\n"+(services==null?"Состояние пока неизвестно. Нажмите «↻ Состояние служб» над списком.":state==null?"Служба не установлена на этом ПК.":state.Detail+" (снимок; обновить кнопкой ↻ над списком)");}
        private async Task ReadHealth(){if(busy)return;SetBusy(true);healthStart.IsEnabled=false;healthProgress.Visibility=Visibility.Visible;healthResult.Text="";healthStatus.Text="Проверяем процессор, память, диски и автозагрузку… Обычно это занимает несколько секунд.";try{var result=await Engine.Run("diagnose","-","-",false,false,value=>{});Get<TextBox>("Output").Text=result.Output;var match=Regex.Match(result.Output,@"(?m)^Report:\s*(.+?)\r?$");if(!match.Success)throw new IOException("Отчёт не создан. Подробности доступны в выводе операции.");var path=Path.GetFullPath(match.Groups[1].Value.Trim());var root=Path.GetFullPath(Path.Combine(Program.Data,"reports"))+Path.DirectorySeparatorChar;if(!path.StartsWith(root,StringComparison.OrdinalIgnoreCase)||new FileInfo(path).Length>2097152)throw new IOException("Некорректный файл отчёта.");var report=new JavaScriptSerializer().Deserialize<Dictionary<string,object>>(File.ReadAllText(path));healthResult.Text=DescribeHealth(report);healthStatus.Text="Снимок получен в "+DateTime.Now.ToString("HH:mm:ss")+(result.Code==0?". Проверка завершена; настройки не менялись.":". Часть данных недоступна; это не означает неисправность ПК.");}catch(Exception ex){healthStatus.Text="Проверка не завершена: "+ex.Message;}finally{healthProgress.Visibility=Visibility.Collapsed;healthStart.IsEnabled=true;SetBusy(false);Text("Status",healthStatus.Text);}await PrepareAutomaticUpdate();}
        private string DescribeHealth(Dictionary<string,object> report){var text=new StringBuilder();object value;var os=report.TryGetValue("os",out value)?value as Dictionary<string,object>:null;if(os!=null){double total=Convert.ToDouble(os["totalMemoryMB"]),free=Convert.ToDouble(os["freeMemoryMB"]);string memory="Свободно памяти: "+(free/1024).ToString("F1")+" из "+(total/1024).ToString("F1")+" ГБ";text.AppendLine(memory);if(priorMemory!=null)text.AppendLine("Предыдущий снимок: "+priorMemory);priorMemory=memory+" ("+DateTime.Now.ToString("HH:mm:ss")+")";if(total>0&&free/total<0.15)text.AppendLine("Мало свободной памяти. Посмотрите крупные процессы ниже и закройте ненужные приложения.");}else text.AppendLine("Память: данные недоступны.");
            foreach(var row in ReportRows(report,"cpu"))text.AppendLine("Процессор: "+row["Name"]+" · Загрузка: "+(row["LoadPercentage"]==null?"нет данных":row["LoadPercentage"]+"%"));
            text.AppendLine("\nМЕСТО НА ДИСКАХ");foreach(var row in ReportRows(report,"disks")){double total=Convert.ToDouble(row["Size"]),free=Convert.ToDouble(row["FreeSpace"]);text.AppendLine(row["DeviceID"]+" · Свободно "+(free/1073741824).ToString("F1")+" из "+(total/1073741824).ToString("F1")+" ГБ"+(total>0&&free/total<0.1?" — мало места, проверьте хранилище":""));}
            text.AppendLine("\nБОЛЬШЕ ВСЕГО ПАМЯТИ СЕЙЧАС");foreach(var row in ReportRows(report,"topMemoryProcesses"))text.AppendLine(row["ProcessName"]+" · "+row["workingSetMB"]+" МБ");text.AppendLine("\nЗаписей автозагрузки найдено: "+ReportRows(report,"startupEntries").Count()+". Это найденные записи, а не количество включённых приложений. Их состояние смотрите в настройках автозагрузки.");if(report.TryGetValue("errors",out value)&&value is System.Collections.IEnumerable)foreach(var error in (System.Collections.IEnumerable)value)text.AppendLine("Недоступные данные: "+error);return text.ToString();}
        private static IEnumerable<Dictionary<string,object>> ReportRows(Dictionary<string,object> report,string key){object value;if(!report.TryGetValue(key,out value)||!(value is System.Collections.IEnumerable))yield break;foreach(var row in (System.Collections.IEnumerable)value){var dict=row as Dictionary<string,object>;if(dict!=null)yield return dict;}}
        private async Task HealthSmoke(){
            var serviceTweak=catalogue.First(t=>t.Kind=="SVC");services=new[]{new ServiceState{Name=serviceTweak.Target,Label="Тест",State="Running",Mode="Manual"}};
            ChooseCollection(new[]{serviceTweak.Id});var card=(ActionRow)Get<ListBox>("Items").Items[0];Assert(card.ServiceStatus.Contains("работает")&&card.ServiceStatus.Contains("вручную"),"Catalogue service card hides current state");Window.UpdateLayout();Capture("portable-ui-service-cards.png");services=new ServiceState[0];Filter();Assert(((ActionRow)Get<ListBox>("Items").Items[0]).ServiceStatus.Contains("Не установлена"),"Absent service confused with disabled service");services=null;Filter();Assert(((ActionRow)Get<ListBox>("Items").Items[0]).ServiceStatus.Contains("неизвестно"),"Unknown service state confused with disabled");Get<Button>("ClearCollection").RaiseEvent(new RoutedEventArgs(Button.ClickEvent));
            services=new[]{new ServiceState{Name="manual-running",Label="Служба по запросу",State="Running",Mode="Manual"},new ServiceState{Name="auto-stopped",Label="Автоматическая служба",State="Stopped",Mode="Auto"}};
            FilterServices();Assert(serviceList.Items.Count==2,"Service snapshot missing rows");runningOnly.IsChecked=true;FilterServices();Assert(serviceList.Items.Count==1&&((ServiceState)serviceList.Items[0]).Mode=="Manual","Running and automatic start conflated");runningOnly.IsChecked=false;serviceSearch.Text="auto-stopped";Assert(serviceList.Items.Count==1,"Service name search failed");serviceSearch.Clear();
            var fixture=new JavaScriptSerializer().Deserialize<Dictionary<string,object>>("{\"os\":{\"totalMemoryMB\":8192,\"freeMemoryMB\":512},\"cpu\":[{\"Name\":\"Test CPU\",\"LoadPercentage\":24}],\"disks\":[{\"DeviceID\":\"C:\",\"Size\":107374182400,\"FreeSpace\":1073741824}],\"topMemoryProcesses\":[{\"ProcessName\":\"Example\",\"workingSetMB\":200}],\"startupEntries\":[],\"errors\":[]}");
            healthResult.Text=DescribeHealth(fixture);Assert(healthResult.Text.Contains("Мало свободной памяти")&&healthResult.Text.Contains("мало места")&&healthResult.Text.Contains("24%"),"Diagnostic advice does not reflect metrics");Assert(DescribeHealth(fixture).Contains("Предыдущий снимок"),"Diagnostic comparison missing");healthStatus.Text="Тестовый снимок для проверки интерфейса";serviceStatus.Text="Тестовые службы: работа и способ запуска показаны отдельно";
            foreach(var size in new[]{new Size(800,600),new Size(1024,768),new Size(1366,768)}){Window.Width=size.Width;Window.Height=size.Height;foreach(int index in new[]{5,6,7,8}){ShowPage(index);Window.UpdateLayout();await Task.Delay(50);Assert(Get<FrameworkElement>(pages[index]).ActualHeight>150,"Health page has no usable viewport");if(size.Width==800)Capture("portable-ui-health-"+index+".png");}}
            services=null;FilterServices();priorMemory=null;await ReadHealth();Assert(healthResult.Text.Length>0,"Actual diagnostic report was not rendered: "+healthStatus.Text);await RefreshServices();ShowPage(0);
        }
        private async Task ReadVerification(){if(busy)return;SetBusy(true);verificationStart.IsEnabled=false;verificationResult.Text="";verificationStatus.Text="Сверяем записи истории с Windows… Ничего не изменяем.";try{var result=await Engine.Run("verify","-","-",false,false,value=>{});Get<TextBox>("Output").Text=result.Output;var rows=Regex.Matches(result.Output,@"(?m)^VERIFY ([A-Z0-9-]+) (MATCH|DRIFT|UNSUPPORTED|ERROR): (.*)$");var text=new StringBuilder();int matched=0,changed=0,unknown=0;foreach(Match row in rows){var item=catalogue.FirstOrDefault(t=>t.Id==row.Groups[1].Value);var status=row.Groups[2].Value;string label;if(status=="MATCH"){matched++;label="Совпадает";}else if(status=="DRIFT"){changed++;label="Изменилась";}else{unknown++;label="Не проверено";}text.AppendLine(label+" · "+(item==null?row.Groups[1].Value:item.Title));}verificationResult.Text=text.ToString();verificationStatus.Text=rows.Count==0?(result.Code==0?"Нет активных записей для проверки. Сначала примените действие из каталога.":"Проверка не завершена. Откройте вывод операции для подробностей."):"Совпадает: "+matched+" · Изменилось: "+changed+" · Не проверено: "+unknown+". Ничего не исправлялось автоматически.";}catch(Exception ex){verificationStatus.Text="Не удалось выполнить проверку: "+ex.Message;}finally{verificationStart.IsEnabled=true;SetBusy(false);Text("Status",verificationStatus.Text);}await PrepareAutomaticUpdate();}
    }
}
