using System;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;

namespace Wintools {
    internal static class ProcessIntegrationTests {
        private static void Assert(bool value,string message){if(!value)throw new Exception(message);}
        internal static void Run(){
            if(!Program.Hosted)throw new InvalidOperationException("Process integration is limited to disposable hosted CI.");
            using(var fixture=Process.Start(new ProcessStartInfo(Path.Combine(Environment.SystemDirectory,"ping.exe"),"-n 90 127.0.0.1"){UseShellExecute=false,CreateNoWindow=true,RedirectStandardOutput=true})){
                try{var row=new ProcessRow{Id=fixture.Id,Started=fixture.StartTime.ToUniversalTime().ToFileTimeUtc(),Name="Temporary process fixture"};var before=ProcessControl.Inspect(row.Id,row.Started);uint target=before.Priority==16384?32u:16384u;var result=ProcessActions.Change(row,before,"priority",target,null);Assert(result.Code==0,result.Output);var changed=ProcessControl.Inspect(row.Id,row.Started);Assert(changed.Priority==target,"Priority not changed");var record=ProcessActions.History().First(r=>r.Pid==row.Id&&!r.Restore);result=ProcessActions.Change(row,changed,"priority",before.Priority,record.Id);Assert(result.Code==0&&ProcessControl.Inspect(row.Id,row.Started).Priority==before.Priority,result.Output);
                    if(before.SupportsAffinity&&(before.Affinity&(before.Affinity-1))!=0){ulong first=before.Affinity&(~before.Affinity+1);result=ProcessActions.Change(row,before,"affinity",first,null);Assert(result.Code==0,result.Output);record=ProcessActions.History().First(r=>r.Pid==row.Id&&r.Action=="affinity"&&!r.Restore);changed=ProcessControl.Inspect(row.Id,row.Started);Assert(changed.Affinity==first,"Affinity not changed");result=ProcessActions.Change(row,changed,"affinity",before.Affinity,record.Id);Assert(result.Code==0&&ProcessControl.Inspect(row.Id,row.Started).Affinity==before.Affinity,result.Output);}
                    Assert(ProcessActions.Change(row,before,"affinity",0,null).Code==4,"Empty affinity accepted");Assert(ProcessActions.Change(row,before,"priority",256,null).Code==4,"Realtime priority accepted");var stale=new ProcessRow{Id=row.Id,Started=row.Started+1,Name=row.Name};Assert(ProcessActions.Change(stale,new ProcessSettings{Id=stale.Id,Started=stale.Started,Priority=before.Priority,Affinity=before.Affinity,SystemAffinity=before.SystemAffinity,SupportsAffinity=before.SupportsAffinity},"priority",target,null).Code==4,"Different process lifetime accepted");
                    string lockPath=Path.Combine(Program.Data,"state","run.lock");using(var gate=new FileStream(lockPath,FileMode.CreateNew,FileAccess.Write,FileShare.None))Assert(ProcessActions.Change(row,before,"priority",target,null).Code==4,"Process ignored engine lock");File.Delete(lockPath);
                    fixture.Kill();fixture.WaitForExit();Assert(ProcessActions.Change(row,before,"priority",target,null).Code==4,"Ended process accepted");
                }finally{if(!fixture.HasExited){fixture.Kill();fixture.WaitForExit();}}
            }
        }
    }
    internal sealed partial class MainWindow {
        private async Task ProcessSmoke(){
            string recordId=Guid.NewGuid().ToString("N"),recordPath=Path.Combine(Program.Data,"process-history",recordId+".json");var read=processRead;var inspect=processInspect;var run=processRun;int calls=0;uint priority=32;ulong affinity=15;var rows=Enumerable.Range(0,100).Select(i=>new ProcessRow{Id=4000+i,Started=10000000+i,Name="Приложение "+i.ToString("D3"),Memory=(100-i)*1048576L}).ToArray();
            try{processRead=()=>rows;processInspect=(pid,start)=>{if(pid==4001)throw new InvalidOperationException("Тест: доступ запрещён");return new ProcessSettings{Id=pid,Started=start,Priority=priority,Affinity=affinity,SystemAffinity=15,SupportsAffinity=true};};processRun=(row,before,action,target,restore)=>{calls++;if(action=="priority")priority=(uint)target;else affinity=target;return Task.FromResult(new EngineResult{Code=0,Output="Тест: реальные процессы не изменялись."});};ShowPage(13);await ReadProcesses();processList.SelectedItem=rows[0];await ReadProcessSettings();Assert(processSettings!=null&&processCpus.Children.Count==4&&!processApplyCpu.IsEnabled,"Process selection settings missing");processPriority.SelectedIndex=1;Assert(processApplyPriority.IsEnabled,"Priority choice unavailable");var cancelled=ChangeProcess("priority",16384);Assert(confirmation!=null,"Priority lacks confirmation");FinishConfirmation(false);await cancelled;Assert(calls==0,"Cancelled process action ran");var apply=ChangeProcess("priority",16384);FinishConfirmation(true);await apply;Assert(calls==1&&processSettings.Priority==16384,"Priority result not refreshed");
                foreach(CheckBox box in processCpus.Children)box.IsChecked=false;Assert(!processApplyCpu.IsEnabled,"Zero CPU selection allowed");((CheckBox)processCpus.Children[0]).IsChecked=true;Assert(processApplyCpu.IsEnabled,"Valid CPU selection rejected");apply=ChangeProcess("affinity",SelectedCpuMask());FinishConfirmation(true);await apply;Assert(calls==2&&processSettings.Affinity==1,"Affinity result not refreshed");
                processList.SelectedItem=rows[1];await ReadProcessSettings();Assert(processSettings==null&&!processApplyPriority.IsEnabled&&processDetail.Text.Contains("недоступно"),"Inaccessible process retained controls");processList.SelectedItem=rows[0];await ReadProcessSettings();SetBusy(true);Assert(!processApplyCpu.IsEnabled&&!processApplyPriority.IsEnabled,"Busy process actions enabled");SetBusy(false);
                foreach(var size in new[]{new Size(1280,800),new Size(800,600)}){Window.Width=size.Width;Window.Height=size.Height;Window.UpdateLayout();await Task.Delay(80);Assert(processList.ActualHeight>230&&processList.ActualWidth>180&&IsVisibleInWindow("NavProcesses")&&IsVisibleInWindow("Verify"),"Process layout clipped: height="+processList.ActualHeight+" width="+processList.ActualWidth+" nav="+IsVisibleInWindow("NavProcesses")+" verify="+IsVisibleInWindow("Verify"));Capture(size.Width==800?"portable-ui-processes-compact.png":"portable-ui-processes.png");}
                Directory.CreateDirectory(Path.GetDirectoryName(recordPath));File.WriteAllText(recordPath,new System.Web.Script.Serialization.JavaScriptSerializer().Serialize(new ProcessChange{Schema="wintools/process-change/1",Id=recordId,Pid=4000,Started=rows[0].Started,Name=rows[0].Name,Action="priority",Before="32",After="16384",Status="OK",TimeUtc=DateTime.UtcNow.ToString("o")}));ReadHistory();Assert(Get<ListBox>("History").Items.Cast<HistoryRow>().Any(r=>r.Run==recordId&&r.ProcessChange&&r.CanRevert),"Process history missing");var restoreTask=RestoreProcessHistory(recordId);for(int i=0;i<100&&confirmation==null&&!restoreTask.IsCompleted;i++)await Task.Delay(10);Assert(confirmation!=null,"Process restore skipped confirmation");FinishConfirmation(true);await restoreTask;Assert(calls==3&&priority==32,"Process history restore failed");File.WriteAllText(recordPath,"{broken");ReadHistory();Assert(Get<ListBox>("History").Items.Count==0,"Corrupt process history accepted");
                processSearch.Text="__missing__";Assert(processList.Items.Count==0&&processSettings==null&&!processApplyPriority.IsEnabled,"Empty process search retained action");processSearch.Clear();
            }finally{if(File.Exists(recordPath))File.Delete(recordPath);processRead=read;processInspect=inspect;processRun=run;ReadHistory();}ShowPage(0);
        }
    }
}
