using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Markup;

namespace Wintools {
    internal sealed partial class MainWindow {
        private ProcessRow[] processRows=new ProcessRow[0];
        private ProcessSettings processSettings;
        private ListBox processList;
        private TextBox processSearch;
        private TextBlock processStatus,processDetail,processCpuStatus;
        private ComboBox processPriority;
        private Button processRefresh,processApplyPriority,processApplyCpu;
        private WrapPanel processCpus;
        private bool readingProcesses,readingProcessSettings;
        private int processSelectionEpoch;
        private Func<ProcessRow[]> processRead=ProcessControl.Read;
        private Func<int,long,ProcessSettings> processInspect=ProcessControl.Inspect;
        private Func<ProcessRow,ProcessSettings,string,ulong,string,Task<EngineResult>> processRun=ProcessActions.Run;
        private void InitializeProcesses(){
            var root=new Grid{Visibility=Visibility.Collapsed};Window.RegisterName("ProcessesPage",root);((Grid)Get<FrameworkElement>("SettingsPage").Parent).Children.Add(root);root.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});root.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});root.RowDefinitions.Add(new RowDefinition());
            var filters=new Grid{Margin=new Thickness(0,0,0,8)};filters.ColumnDefinitions.Add(new ColumnDefinition());filters.ColumnDefinitions.Add(new ColumnDefinition{Width=GridLength.Auto});root.Children.Add(filters);processSearch=new TextBox{Margin=new Thickness(0,0,10,0)};System.Windows.Automation.AutomationProperties.SetName(processSearch,"Поиск процесса по имени или PID");filters.Children.Add(processSearch);var hint=Paragraph("Имя программы или PID…");hint.IsHitTestVisible=false;hint.Margin=new Thickness(12,0,10,0);hint.VerticalAlignment=VerticalAlignment.Center;filters.Children.Add(hint);processSearch.TextChanged+=(s,e)=>{hint.Visibility=processSearch.Text.Length==0?Visibility.Visible:Visibility.Collapsed;FilterProcesses();};processRefresh=new Button{Content="Обновить"};Grid.SetColumn(processRefresh,1);filters.Children.Add(processRefresh);processRefresh.Click+=async(s,e)=>await ReadProcesses();
            processStatus=Paragraph("Выберите процесс. Список отсортирован по используемой памяти.");Grid.SetRow(processStatus,1);root.Children.Add(processStatus);
            var body=new Grid();body.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(2,GridUnitType.Star)});body.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(3,GridUnitType.Star)});Grid.SetRow(body,2);root.Children.Add(body);
            processList=new ListBox{HorizontalContentAlignment=HorizontalAlignment.Stretch,Margin=new Thickness(0,0,10,0)};VirtualizingPanel.SetIsVirtualizing(processList,true);VirtualizingPanel.SetVirtualizationMode(processList,VirtualizationMode.Recycling);ScrollViewer.SetCanContentScroll(processList,true);body.Children.Add(processList);processList.ItemTemplate=(DataTemplate)XamlReader.Parse("<DataTemplate xmlns='http://schemas.microsoft.com/winfx/2006/xaml/presentation'><StackPanel><TextBlock Text='{Binding Name}' FontWeight='SemiBold' TextTrimming='CharacterEllipsis'/><TextBlock Text='{Binding Detail}' Foreground='{DynamicResource Muted}' FontSize='12' TextWrapping='Wrap' Margin='0,4,0,0'/></StackPanel></DataTemplate>");var rowStyle=new Style(typeof(ListBoxItem),(Style)Window.FindResource(typeof(ListBoxItem)));rowStyle.Setters.Add(new Setter(Control.PaddingProperty,new Thickness(10,8,10,8)));rowStyle.Setters.Add(new Setter(FrameworkElement.MarginProperty,new Thickness(0,0,0,4)));processList.ItemContainerStyle=rowStyle;processList.SelectionChanged+=async(s,e)=>await ReadProcessSettings();
            var panel=new StackPanel();var scroll=new ScrollViewer{Content=panel,VerticalScrollBarVisibility=ScrollBarVisibility.Auto,Padding=new Thickness(4,0,8,0)};Grid.SetColumn(scroll,1);body.Children.Add(scroll);processDetail=Paragraph("Выберите программу слева. Настройки применяются только к выбранному запуску.");panel.Children.Add(processDetail);
            panel.Children.Add(Paragraph("Приоритет процессора"));processPriority=new ComboBox{ItemsSource=ProcessControl.Priorities.Select(ProcessControl.PriorityName).ToArray(),SelectedIndex=2,Margin=new Thickness(0,0,0,8)};System.Windows.Automation.AutomationProperties.SetName(processPriority,"Новый приоритет процесса");processPriority.SelectionChanged+=(s,e)=>RefreshProcessEnabled();panel.Children.Add(processPriority);panel.Children.Add(Paragraph("Определяет, кому раньше достанется время CPU при нагрузке. Повышение может замедлить другие программы; больше FPS оно не гарантирует."));processApplyPriority=new Button{Content="Применить приоритет",Margin=new Thickness(0,0,0,14),HorizontalAlignment=HorizontalAlignment.Left};processApplyPriority.Click+=async(s,e)=>{if(processPriority.SelectedIndex>=0)await ChangeProcess("priority",ProcessControl.Priorities[processPriority.SelectedIndex]);};panel.Children.Add(processApplyPriority);
            panel.Children.Add(Paragraph("Доступные логические процессоры"));processCpuStatus=Paragraph("Состояние ещё не прочитано.");panel.Children.Add(processCpuStatus);processCpus=new WrapPanel();panel.Children.Add(processCpus);processApplyCpu=new Button{Content="Применить набор CPU",Margin=new Thickness(0,8,0,12),HorizontalAlignment=HorizontalAlignment.Left};processApplyCpu.Click+=async(s,e)=>await ChangeProcess("affinity",SelectedCpuMask());panel.Children.Add(processApplyCpu);panel.Children.Add(Paragraph("Ограничение набора CPU может снизить производительность. Прежнее значение сохраняется в истории и возвращается, пока этот запуск работает. Дочерние процессы могут наследовать настройку; их параметры отдельно не возвращаются."));
            root.IsVisibleChanged+=async(s,e)=>{if(root.IsVisible&&!smoke)await ReadProcesses();};RefreshProcessEnabled();
        }
        private ulong SelectedCpuMask(){ulong mask=0;if(processCpus!=null)foreach(CheckBox item in processCpus.Children)if(item.IsChecked==true)mask|=1UL<<(int)item.Tag;return mask;}
        private void RefreshProcessEnabled(){if(processApplyCpu==null)return;bool enabled=!busy&&!readingProcesses&&!readingProcessSettings&&processSettings!=null;processRefresh.IsEnabled=!busy&&!readingProcesses;processPriority.IsEnabled=enabled;processCpus.IsEnabled=enabled&&processSettings.SupportsAffinity;processApplyPriority.IsEnabled=enabled&&processPriority.SelectedIndex>=0&&ProcessControl.Priorities[processPriority.SelectedIndex]!=processSettings.Priority;ulong mask=SelectedCpuMask();processApplyCpu.IsEnabled=enabled&&processSettings.SupportsAffinity&&mask!=0&&mask!=processSettings.Affinity;}
        private void FilterProcesses(){if(processList==null)return;var prior=processList.SelectedItem as ProcessRow;string query=processSearch.Text.Trim();var rows=processRows.Where(r=>(r.Name+" "+r.Id).IndexOf(query,StringComparison.CurrentCultureIgnoreCase)>=0).ToArray();processList.ItemsSource=rows;processList.SelectedItem=prior==null?null:rows.FirstOrDefault(r=>r.Id==prior.Id&&r.Started==prior.Started);processStatus.Text="Показано: "+rows.Length+" · По убыванию памяти. Изменения доступны для поддерживаемых процессов вашего пользователя.";}
        private async Task ReadProcesses(){if(busy||readingProcesses)return;readingProcesses=true;RefreshProcessEnabled();try{var read=processRead;var rows=await Task.Run(()=>read());if(closed)return;processRows=rows;FilterProcesses();}catch(Exception ex){processRows=new ProcessRow[0];processList.ItemsSource=null;processStatus.Text="Не удалось прочитать процессы: "+ex.Message;}finally{readingProcesses=false;RefreshProcessEnabled();}}
        private async Task ReadProcessSettings(){
            int epoch=++processSelectionEpoch;var row=processList.SelectedItem as ProcessRow;processSettings=null;processCpus.Children.Clear();readingProcessSettings=row!=null;RefreshProcessEnabled();if(row==null){processDetail.Text="Выберите программу слева.";processCpuStatus.Text="";return;}processDetail.Text="Читаем настройки «"+row.Name+"»…";
            try{var inspect=processInspect;var settings=await Task.Run(()=>inspect(row.Id,row.Started));if(closed||epoch!=processSelectionEpoch)return;processSettings=settings;processDetail.Text=row.Name+" · PID "+row.Id+"\nСейчас: "+ProcessControl.PriorityName(settings.Priority)+" приоритет.";processPriority.SelectedIndex=Array.IndexOf(ProcessControl.Priorities,settings.Priority);if(settings.SupportsAffinity){for(int i=0;i<64;i++){if((settings.SystemAffinity&(1UL<<i))==0)continue;var box=new CheckBox{Content="CPU "+i,Tag=i,IsChecked=(settings.Affinity&(1UL<<i))!=0,Margin=new Thickness(0,0,10,8)};box.Checked+=(s,e)=>RefreshProcessEnabled();box.Unchecked+=(s,e)=>RefreshProcessEnabled();processCpus.Children.Add(box);}processCpuStatus.Text="Отмечены разрешённые процессоры. Оставьте хотя бы один.";}else processCpuStatus.Text="Редактор CPU недоступен для этого процесса или системы с несколькими группами процессоров.";
            }catch(Exception ex){if(epoch!=processSelectionEpoch||closed)return;processSettings=null;processDetail.Text=row.Name+": управление недоступно. "+ex.Message;processCpuStatus.Text="Состояние неизвестно.";}
            finally{if(epoch==processSelectionEpoch){readingProcessSettings=false;RefreshProcessEnabled();}}
        }
        private async Task ChangeProcess(string action,ulong target){var row=processList.SelectedItem as ProcessRow;var before=processSettings;if(busy||readingProcessSettings||row==null||before==null)return;try{ProcessControl.ValidateTarget(action,target,before);if(ProcessControl.Value(before,action)==target)return;if(!await Confirm("Изменить «"+row.Name+"» · PID "+row.Id+"?\n\n"+(action=="priority"?"Новый приоритет: "+ProcessControl.PriorityName((uint)target)+". Высокий приоритет может замедлить другие программы.":"Изменится набор логических процессоров, на которых разрешено работать программе. Ограничение может снизить её производительность.")+"\n\nНастройка действует для текущего запуска. Прежнее значение сохранится в истории. Параметры дочерних процессов отдельно не возвращаются."))return;await RunProcessChange(row,before,action,target,null);}catch(Exception ex){Text("Status",ex.Message);}}
        private async Task RunProcessChange(ProcessRow row,ProcessSettings before,string action,ulong target,string restore){if(busy)return;SetBusy(true);try{var result=await processRun(row,before,action,target,restore);Get<TextBox>("Output").Text=result.Output;Text("Status",result.Code==0?"Настройка процесса сохранена.":"Настройка процесса требует внимания. Причина — в выводе.");if(result.Code!=0)ExpandOutput(true);}catch(Exception ex){Text("Status","Процесс не изменён: "+ex.Message);}finally{SetBusy(false);}ReadHistory();await ReadProcessSettings();}
        private async Task RestoreProcessHistory(string id){if(busy)return;try{var record=ProcessActions.Read(id);if(record.Restore||record.Status=="REVERTED")throw new InvalidOperationException("Это изменение уже возвращено.");var inspect=processInspect;var before=await Task.Run(()=>inspect(record.Pid,record.Started));if(ProcessControl.Value(before,record.Action)!=ulong.Parse(record.After))throw new InvalidOperationException("Настройка изменена позднее. Сначала верните более новое изменение.");if(!await Confirm("Вернуть прежнюю настройку «"+record.Name+"» · PID "+record.Pid+"?\n\nВозврат относится только к этому запуску программы, без изменения дочерних процессов."))return;await RunProcessChange(new ProcessRow{Id=record.Pid,Started=record.Started,Name=record.Name},before,record.Action,ulong.Parse(record.Before),id);}catch(Exception ex){Text("Status","Не удалось вернуть настройку процесса: "+ex.Message);}}
        private static HistoryRow[] ProcessHistoryRows(){return ProcessActions.History().Select(r=>new HistoryRow{Run=r.Id,ProcessChange=true,TimeUtc=DateTime.Parse(r.TimeUtc,System.Globalization.CultureInfo.InvariantCulture,System.Globalization.DateTimeStyles.RoundtripKind),Title=(r.Restore?"Возврат · ":"")+r.Name+" · "+(r.Action=="priority"?"приоритет":"набор CPU"),Status=r.Status=="OK"?"Применено":r.Status=="REVERTED"?"Откат выполнен":"Требует внимания",CanRevert=!r.Restore&&r.Status!="REVERTED"}).ToArray();}
    }
}
