using System;
using System.Linq;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Markup;

namespace Wintools {
    internal sealed partial class MainWindow {
        private StartupSnapshot startupSnapshot;
        private ListBox startupList;
        private TextBox startupSearch;
        private ComboBox startupFilter;
        private TextBlock startupStatus,startupDetail;
        private Button startupRefresh,startupEnable,startupDisable;
        private bool readingStartup,startupReadPending;
        private int startupEpoch;
        private Func<StartupSnapshot> startupRead=StartupEntries.Read;
        private Func<StartupEntry,string,string,Task<EngineResult>> startupRun=StartupActions.Run;
        private void InitializeStartup(){
            var root=new Grid{Visibility=Visibility.Collapsed};Window.RegisterName("StartupPage",root);((Grid)Get<FrameworkElement>("SettingsPage").Parent).Children.Add(root);
            foreach(var height in new[]{GridLength.Auto,GridLength.Auto,GridLength.Auto,new GridLength(1,GridUnitType.Star),GridLength.Auto,GridLength.Auto})root.RowDefinitions.Add(new RowDefinition{Height=height});
            var intro=Paragraph("Программы из реестра Run и папок автозагрузки. Отключение убирает запуск при следующем входе в Windows, но не закрывает уже работающую программу. Задачи планировщика и автозапуск Store сюда пока не входят.");root.Children.Add(intro);
            var filters=new Grid{Margin=new Thickness(0,0,0,8)};filters.ColumnDefinitions.Add(new ColumnDefinition());filters.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(145)});Grid.SetRow(filters,1);root.Children.Add(filters);
            startupSearch=new TextBox{Margin=new Thickness(0,0,10,0),ToolTip="Поиск по имени, команде и источнику"};System.Windows.Automation.AutomationProperties.SetName(startupSearch,"Поиск в автозагрузке");filters.Children.Add(startupSearch);var searchHint=new TextBlock{Text="Найти программу или команду…",IsHitTestVisible=false,VerticalAlignment=VerticalAlignment.Center,Margin=new Thickness(12,0,10,0)};searchHint.SetResourceReference(TextBlock.ForegroundProperty,"Muted");filters.Children.Add(searchHint);startupSearch.TextChanged+=(s,e)=>{searchHint.Visibility=startupSearch.Text.Length==0?Visibility.Visible:Visibility.Collapsed;FilterStartup();};
            startupFilter=new ComboBox{ItemsSource=new[]{"Все записи","Включённые","Отключённые","Неизвестно"},SelectedIndex=0};System.Windows.Automation.AutomationProperties.SetName(startupFilter,"Состояние автозагрузки");Grid.SetColumn(startupFilter,1);filters.Children.Add(startupFilter);startupFilter.SelectionChanged+=(s,e)=>FilterStartup();
            startupStatus=Paragraph("Нажмите «Обновить список», чтобы прочитать автозагрузку.");Grid.SetRow(startupStatus,2);root.Children.Add(startupStatus);
            startupList=new ListBox{HorizontalContentAlignment=HorizontalAlignment.Stretch};Grid.SetRow(startupList,3);root.Children.Add(startupList);VirtualizingPanel.SetIsVirtualizing(startupList,true);VirtualizingPanel.SetVirtualizationMode(startupList,VirtualizationMode.Recycling);ScrollViewer.SetCanContentScroll(startupList,true);
            var rowStyle=new Style(typeof(ListBoxItem),(Style)Window.FindResource(typeof(ListBoxItem)));rowStyle.Setters.Add(new Setter(Control.PaddingProperty,new Thickness(10,6,10,6)));rowStyle.Setters.Add(new Setter(FrameworkElement.MarginProperty,new Thickness(0,0,0,4)));startupList.ItemContainerStyle=rowStyle;
            startupList.ItemTemplate=(DataTemplate)XamlReader.Parse("<DataTemplate xmlns='http://schemas.microsoft.com/winfx/2006/xaml/presentation'><Grid><Grid.ColumnDefinitions><ColumnDefinition Width='*'/><ColumnDefinition Width='105'/></Grid.ColumnDefinitions><StackPanel Margin='0,0,12,0'><TextBlock Text='{Binding Name}' FontWeight='SemiBold' TextTrimming='CharacterEllipsis'/><TextBlock Text='{Binding Location}' Foreground='{DynamicResource Muted}' FontSize='12' Margin='0,4,0,0'/><TextBlock Text='{Binding Command}' ToolTip='{Binding Command}' Foreground='{DynamicResource Muted}' FontSize='12' TextTrimming='CharacterEllipsis' Margin='0,4,0,0'/></StackPanel><TextBlock Grid.Column='1' Text='{Binding State}' VerticalAlignment='Center'/></Grid></DataTemplate>");startupList.SelectionChanged+=(s,e)=>{var selected=startupList.SelectedItem as StartupEntry;startupDetail.Text=selected==null?"Выберите программу. Исходное состояние сохраняется в истории.":selected.Error??("«"+selected.Name+"» · "+selected.Location+". Отключайте только программы, которые не нужны сразу после входа; например, мессенджер перестанет автоматически показывать сообщения.");RefreshStartupEnabled();};
            startupDetail=Paragraph("Выберите программу. Исходное состояние сохраняется в истории.");startupDetail.FontSize=12;startupDetail.Margin=new Thickness(0,8,0,8);Grid.SetRow(startupDetail,4);root.Children.Add(startupDetail);
            var buttons=new WrapPanel();Grid.SetRow(buttons,5);root.Children.Add(buttons);startupDisable=new Button{Content="Отключить при входе",Margin=new Thickness(0,0,8,4)};startupDisable.Click+=async(s,e)=>await ChangeStartup(false);buttons.Children.Add(startupDisable);startupEnable=new Button{Content="Включить при входе",Margin=new Thickness(0,0,8,4)};startupEnable.Click+=async(s,e)=>await ChangeStartup(true);buttons.Children.Add(startupEnable);startupRefresh=new Button{Content="Обновить список",Margin=new Thickness(0,0,0,4)};startupRefresh.Click+=async(s,e)=>await ReadStartup();buttons.Children.Add(startupRefresh);
            root.IsVisibleChanged+=async(s,e)=>{if(root.IsVisible&&!smoke)await ReadStartup();};RefreshStartupEnabled();
        }
        private void RefreshStartupEnabled(){if(startupList==null)return;var selected=startupList.SelectedItem as StartupEntry;bool available=!busy&&!readingStartup;startupRefresh.IsEnabled=available;startupEnable.IsEnabled=available&&selected!=null&&selected.Enabled==false;startupDisable.IsEnabled=available&&selected!=null&&selected.Enabled==true;}
        private void FilterStartup(){
            if(startupList==null)return;string key=(startupList.SelectedItem as StartupEntry)==null?null:((StartupEntry)startupList.SelectedItem).Key;string query=startupSearch.Text.Trim();var rows=(startupSnapshot==null?new StartupEntry[0]:startupSnapshot.Entries).Where(r=>(r.Name+" "+r.Command+" "+r.Location).IndexOf(query,StringComparison.CurrentCultureIgnoreCase)>=0&&(startupFilter.SelectedIndex==0||startupFilter.SelectedIndex==1&&r.Enabled==true||startupFilter.SelectedIndex==2&&r.Enabled==false||startupFilter.SelectedIndex==3&&!r.Enabled.HasValue)).ToArray();startupList.ItemsSource=rows;startupList.SelectedItem=rows.FirstOrDefault(r=>r.Key==key);if(startupSnapshot!=null)startupStatus.Text="Показано: "+rows.Length+" из "+startupSnapshot.Entries.Length+" · Включено: "+startupSnapshot.Entries.Count(r=>r.Enabled==true)+" · Отключено: "+startupSnapshot.Entries.Count(r=>r.Enabled==false)+" · Неизвестно: "+startupSnapshot.Entries.Count(r=>!r.Enabled.HasValue)+(startupSnapshot.Errors.Length==0?"":". Не все источники прочитаны: "+string.Join("; ",startupSnapshot.Errors));RefreshStartupEnabled();
        }
        private async Task ReadStartup(){
            if(busy)return;if(readingStartup){startupReadPending=true;return;}
            do {
                startupReadPending=false;int epoch=startupEpoch;readingStartup=true;RefreshStartupEnabled();startupStatus.Text="Читаем записи и состояние Windows…";
                try{var read=startupRead;var result=await Task.Run(()=>read());if(closed)return;if(epoch!=startupEpoch)startupReadPending=true;else{startupSnapshot=result;FilterStartup();}}
                catch(Exception ex){if(epoch!=startupEpoch)startupReadPending=true;else{startupSnapshot=null;startupList.ItemsSource=null;startupStatus.Text="Не удалось прочитать автозагрузку: "+ex.Message;}}
                finally{readingStartup=false;if(!closed)RefreshStartupEnabled();}
            }while(startupReadPending&&!busy&&!closed);
        }
        private async Task ChangeStartup(bool enabled){var entry=startupList.SelectedItem as StartupEntry;if(busy||readingStartup||entry==null||!entry.Enabled.HasValue||entry.Enabled.Value==enabled)return;if(!await Confirm((enabled?"Включить":"Отключить")+" запуск «"+entry.Name+"» при входе в Windows?\n\n"+entry.Location+"\n"+entry.Command+"\n\n"+(enabled?"При следующем входе Windows сможет запустить эту команду.":"Программа не запустится через эту запись. Её уведомления, синхронизация и другие фоновые функции могут стать недоступны до ручного запуска.")+" Уже работающие процессы не изменятся. Прежнее состояние можно вернуть через историю."))return;await RunStartupChange(entry,enabled?"enable":"disable",null);}
        private async Task RunStartupChange(StartupEntry entry,string action,string restore){if(busy)return;SetBusy(true);try{var result=await startupRun(entry,action,restore);Get<TextBox>("Output").Text=result.Output;Text("Status",result.Code==0?"Состояние автозагрузки сохранено.":"Изменение требует внимания. Причина — в выводе.");if(result.Code!=0)ExpandOutput(true);}catch(Exception ex){Text("Status","Автозагрузка не изменена: "+ex.Message);}finally{SetBusy(false);}ReadHistory();await ReadStartup();}
        private async Task RestoreStartupHistory(string id){if(busy)return;try{var record=StartupActions.Read(id);if(record.Action=="restore"||record.Status=="REVERTED")throw new InvalidOperationException("Это изменение уже возвращено.");var entry=await Task.Run(()=>StartupEntries.Inspect(record.Source,record.Name));if(entry.Identity!=record.Identity||entry.Approval!=record.After)throw new InvalidOperationException("Запись изменилась. Сначала отмените более поздние изменения; прежнее состояние не будет записано поверх чужого изменения.");if(!await Confirm("Вернуть прежнюю автозагрузку «"+record.Name+"»?\n\nБудет восстановлено состояние до выбранного изменения: "+(StartupEntries.Decode(record.Before)==true?"включено":"отключено")+". Изменение относится к следующему входу в Windows."))return;await RunStartupChange(entry,"restore",id);}catch(Exception ex){Text("Status","Не удалось вернуть автозагрузку: "+ex.Message);}}
        private static HistoryRow[] StartupHistoryRows(){return StartupActions.History().Select(r=>new HistoryRow{Run=r.Id,StartupChange=true,TimeUtc=DateTime.Parse(r.TimeUtc,System.Globalization.CultureInfo.InvariantCulture,System.Globalization.DateTimeStyles.RoundtripKind),Title=(r.Action=="restore"?"Возврат автозагрузки: ":r.Action=="enable"?"Автозагрузка включена: ":"Автозагрузка отключена: ")+r.Name,Status=r.Status=="OK"?"Применено":r.Status=="REVERTED"?"Откат выполнен":"Требует внимания",CanRevert=r.Action!="restore"&&r.Status!="REVERTED"}).ToArray();}
    }
}
